### ISSUE TITLE
uninitialized constant PageValidations::HTMLValidation::FileUtils

### ISSUE THREAD

**Issue by jwoertink** [ericbeland/html_validation#7]
Using ruby 2.1.2 when doing 

```ruby
h = PageValidations::HTMLValidation.new
```
I get the error. Doing a `require 'fileutils'` before fixes this.

**Comment by ahmetabdi** [comment]
? Still occurs

**Comment by ericbeland** [comment]
Should be fixed in 1.1.3.  Had no idea it was still an issue. Wish someone would have said something sooner, or done a PR. Anyhow, I'm closing this. If it still happens in 1.1.3+ let me know.
